### ISSUE TITLE
Open source checklist

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-custodians-library#20]
- [x] Readme (include a code of conduct and contributing guide section)
- [ ] DCO
- [x] Licence file
- [x] Licence headers

- [ ] SonarQube
- [x] Github actions
- [ ] Code Coverage
- [x] Branch protection rules
- [ ] ~~Add project to Hedera docs site when live (if required)~~
- [ ] ~~Standardize package name (com.hedera.<name>) (if applicable)~~
- [X] Add [security.md](http://security.md/) file if the project is not going to be part of the bug bounty program
- [ ] ~~Approval from council (if required)~~
- [ ] ~~Code audit before open sourcing (If required)~~

- [ ] Open source project
